stages:
    - deploy
heroku:
    stage: deploy
    script:
        - gem install dpl
        - dpl --provider=heroku --app=loilo --api-key=$HEROKU_API_KEY
    only:
        - tags

pages:
  stage: deploy
  script:
    - mv pages public
  artifacts:
    paths:
      - public
  only:
    - master