stages:
    - build
    - test
    - deploy

test:
  image: alpine:latest
  services:
    - ${CI_REGISTRY_IMAGE}:$CI_COMMIT_TAG
  stage: test
  before_script:
    - apk add curl
  script:
    - "[ $(curl $(echo ${CI_REGISTRY_IMAGE}|sed s./.-.g):3000/api -w \"%{http_code}\" --retry 5 --retry-connrefused) = \"308\" ]"
    - "[ $(curl $(echo ${CI_REGISTRY_IMAGE}|sed s./.-.g):3000/api/web_filtering) = \"{\\\"type\\\":\\\"none\\\"}\" ]"
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+.*$/
      when: always

heroku:
    image: ruby:latest
    stage: deploy
    script:
        - gem install dpl
        - dpl --provider=heroku --app=loilo --api-key=$HEROKU_API_KEY
        - "[ $(curl loilo.herokuapp.com/api -w \"%{http_code}\") -lt \"500\" ]"
    rules:
        - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+.*$/
          when: manual

docker:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  before_script: 
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - export CONTAINER_ID=$(docker build . -q)
    - docker tag ${CONTAINER_ID} ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}:latest
    - docker tag ${CONTAINER_ID} ${CI_REGISTRY_IMAGE}:$CI_COMMIT_TAG
    - docker push ${CI_REGISTRY_IMAGE}:$CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+.*$/
      when: always
