stages:
    - build
    - test
    - deploy

test:
  image: alpine:latest
  services:
    - ${CI_REGISTRY_IMAGE}:$CI_COMMIT_TAG
  stage: test
  before_script:
    - apk add curl
  script:
    - "[ $(curl $(echo ${CI_REGISTRY_IMAGE}|sed s./.-.g):3000/api -w \"%{http_code}\" --retry 5 --retry-connrefused) = \"308\" ]"
    - "[ $(curl $(echo ${CI_REGISTRY_IMAGE}|sed s./.-.g):3000/api/web_filtering) = \"{\\\"type\\\":\\\"none\\\"}\" ]"
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+.*$/
      when: always

heroku:
  image: alpine:latest
  stage: deploy
  before_script:
    - apk add jq curl
  script:
    - export CONTAINER_ID=$(curl -u ":$HEROKU_API_KEY" "https://registry.heroku.com/v2/$HEROKU_APPNAME/web/manifests/$CI_COMMIT_TAG" -H "Accept":" application/vnd.docker.distribution.manifest.v2+json"|jq -r ".config.digest")
    - echo Deploying $CONTAINER_ID
    - "curl -X PATCH https://api.heroku.com/apps/$HEROKU_APPNAME/formation -d
    '{\"updates\": [{\"type\": \"web\",\"docker_image\":\"'$CONTAINER_ID'\"}]}'
    -H \"Content-Type: application/json\"
    -H \"Accept: application/vnd.heroku+json; version=3.docker-releases\"
    -H \"Authorization: Bearer $HEROKU_API_KEY\""
    - "[ $(curl loilo.herokuapp.com/api -w \"%{http_code}\") -lt \"500\" ]"
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+.*$/
      when: manual

docker:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  before_script: 
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker login -u "_" -p $HEROKU_API_KEY registry.heroku.com
  script:
    - export CONTAINER_ID=$(docker build . -q)
    - docker tag ${CONTAINER_ID} ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}:latest
    - docker tag ${CONTAINER_ID} ${CI_REGISTRY_IMAGE}:$CI_COMMIT_TAG
    - docker push ${CI_REGISTRY_IMAGE}:$CI_COMMIT_TAG
    - docker tag ${CONTAINER_ID} registry.heroku.com/$HEROKU_APPNAME/web:$CI_COMMIT_TAG
    - docker push registry.heroku.com/$HEROKU_APPNAME/web:$CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+.*$/
      when: always
