stages:
    - deploy
heroku:
    stage: deploy
    script:
        - gem install dpl
        - dpl --provider=heroku --app=loilo --api-key=$HEROKU_API_KEY
    only:
        - tags
        - web
pages:
  image: alpine:latest
  stage: deploy
  script:
    - ":"
  artifacts:
    paths:
      - public
  only:
    changes:
        - public/*
